### ISSUE TITLE
Friendlier error message when ocsms app is not installed on server

### ISSUE THREAD

**Issue by jreybert** [nerzhul/ocsms#60]
Hi,

it may seems dumb, but I stucked because of the error:
Error #15: Unable to parse server response

As I downloaded and installed from f-droid, I missed the server part. If it is possible, an error message precising that the server app part is missing may save some time.

**Comment by nerzhul** [comment]
Please use google play store and not F-Droid. F-Droid build doesn't support HTTPS self signed certficates.

**Comment by jreybert** [comment]
Hm, ok, I may use google play instead of f-droid.

Anyway, I don't get why you closed the issue?

**Comment by nerzhul** [comment]
Hmmm strange right, i re-open it

**Comment by nerzhul** [comment]
Now i see, it was closed because the error is due to owncloud library which is included in owncloud SMS APP and modified for Google Play Store to accept self signed certificates. Later, i will remove this lib and use an embedded lib to interact with ownCloud, but not yet.

I reclose this issue which is due to F-Droid, we doesn't support it.
